[package]
name = "rustylcm"
version = "0.1.0"
authors = ["jakobneufeld <jakob.n.neufeld@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
